#!/bin/bash
pushd ${0%/*}
mkdir -p pack/pack/start
pushd pack/pack/start
(git clone git@github.com:editorconfig/editorconfig-vim --single-branch &
git clone git@github.com:xero/sourcerer.vim --single-branch &
git clone git@github.com:justinmk/vim-sneak --single-branch &
git clone git@github.com:tpope/vim-sleuth --single-branch &
git clone git@github.com:neoclide/coc.nvim -b release --single-branch &
wait
) 2>/dev/null
popd
for d in pack/pack/start/*
do pushd "$d"
git pull
popd
done
popd
